form.addEventListener("submit", function(event) {
    event.preventDefault();
    handleRegisterForm(event);
});

var email = document.getElementById("email");
var username = document.getElementById("username");
var namep = document.getElementById("name");
var password = document.getElementById("password");
var rpassword = document.getElementById("rpassword");



function validateUsername(username) {
    const usernameRegex = /^[a-zA-Z0-9]+$/;
    return username.length >= 4 && usernameRegex.test(username);
}

function validateName(name) {
    const nameRegex = /^[a-zA-Z]+$/;
    return nameRegex.test(name);
}

function validatePassword(password) {
    const minLength = 8;
    const uppercaseRegex = /[A-Z]/;
    const lowercaseRegex = /[a-z]/;
    const digitRegex = /[0-9]/;
    return (
        password.length >= minLength &&
        uppercaseRegex.test(password) &&
        lowercaseRegex.test(password) &&
        digitRegex.test(password)
    );
}

username.addEventListener('input', function() {
    if(validateUsername(username.value)){
        username.setCustomValidity('');
    } else{
        username.setCustomValidity('Your username needs to be atleast 4 characters and can only contain numbers and letters')
    }
});

email.addEventListener('input', function(){
    const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if(!emailRegex.test(email.value)){
        email.setCustomValidity('Please enter an email address which is valid'); 
        return; 
    }  else email.setCustomValidity(''); 
});

namep.addEventListener('input', function(){
    if(!validateName(namep.value)){
        namep.setCustomValidity('Your name can only contain letters');
        return;
    } else {namep.setCustomValidity('');}

});
function handleRegisterForm(event){
    if(!password.value == rpassword.value){
        alert("the passwords arent the same");
        return;
    } 
 
    if(!validatePassword(password.value)){
        alert('Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one digit');
        return;
    }

    registerUser();
}

function generateJson(email, name, password, username){
    var data = {
        id: 0,
        name: name,
        email: email,
        password: password,
        username: username
    };
    return data;
}

//function generated by Chat GTP
 async function hashPassword(password) {
    // Create a new instance of the SHA-256 hash function
    const sha256 = crypto.subtle.digest('SHA-256', new TextEncoder().encode(password));
    
    // Convert the result to a hexadecimal string
    return sha256.then(buffer => {
        const hashArray = Array.from(new Uint8Array(buffer));
        const hashedPassword = hashArray.map(byte => byte.toString(16).padStart(2, '0')).join('');
        return hashedPassword;
    });
}

 async function registerUser(){
    var passwordcrypted = await hashPassword(password.value);
    console.log(passwordcrypted);
    var data = generateJson(email.value, namep.value, passwordcrypted, username.value);

    fetch('https://localhost:7212/api/User', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin' : '*'
        },
        body: JSON.stringify(data)
    }).then(response => {
        return response.text();
    }).then(data => {
     console.log(data);
      if (data == "true") {
        
      } else {
        alert("er is al een account met deze email of username");
      }
    })
    .catch(error => {
    
    });
}